### ISSUE TITLE
Objectmeta of embedded object goes missing during CRD conversion

### ISSUE THREAD

**Issue by champak** [kubernetes-sigs/controller-tools#448] opened 2020-05-29 15:33 UTC
Hi folks,
I ran into an odd issue with CRD conversion using controller-tools v0.2.4/kubebuilder 2.2.0/apiserver 17.1 This CRD has embedded native specs like the PodTemplateSpec in its spec. I found that in the conversion functions the ObjectMeta of the embedded PodTemplateSpec is nulled out. Other attributes look OK. There is nothing in the validation callback. I had needed to add preserveUnknownFields: false to the CRD to be able to deploy the yaml; not sure if that has some sideffect

The ObjectMeta for the CRD itself shows up fine. It is the embedded spec's ObjectMeta that seemed to be affected. Does this sound like any known issue ? One that looked somewhat related from a search was kubernetes-sigs/controller-tools#279 with comments from @DirectXMan12 but was not quite the same problem.
Thanks for any insight !

**Comment by DirectXMan12** [comment] 2020-06-01 23:07
/kind bug
/priority critical-urgent
/needs-more-info

any idea if this is happening during the conversion webhook?  Can you post a reproducer?

**Comment by champak** [comment] 2020-06-02 02:15
I had added logs to the ConvertTo(dstRaw conversion.Hub) and ConvertFrom(srcRaw conversion.Hub) functions in the file api/v<>/<>_conversion.go to display the contents of the ObjectMeta from the CRD and the embedded PodTemplateSpec. The ObjectMeta.Name etc from the CRD level had the expected contents but the contents from the embedded podtemplatespec were nulled.   Are there other places that may be useful to log ? I was wondering if the api-server itself could have chosen to not send the metadata of the embedded spec to the webhook. Have not looked yet at what all layers are in play between the api-server and the ConvertTo/From functions. I am wondering if I am missing some knob. I was following the kubebuilder book on the conversion.

The CRD structure is on the lines of ;
CRDfooSpec {
<name> barspec
}
barspec {
Pod corev1.PodTemplateSpec  ...
...
}


 The embedded podtemplate spec contents are visible in the last-applied-configuration annotation of the CRD so the info did make it to the api-server. I will try to post a repro. Thanks !

**Comment by champak** [comment] 2020-06-02 20:04
I created a simple repro for this issue.  @DirectXMan12 please see https://github.com/champak/repro-kbuilder-version-issue . 

If the sample yaml at https://github.com/champak/repro-kbuilder-version-issue/blob/master/config/samples/left_v1alpha1_repro.yaml

is applied, the logs at the webhook converter look like

2020/06/02 19:42:14 ConvertFrom : working on repro-sample 
2020/06/02 19:42:14 ConvertFrom working on Pod  attr bar  ===> I tried printing the pod name; nothing shows up.
2020/06/02 19:42:30 ConvertFrom : working on repro-sample 
2020/06/02 19:42:30 ConvertFrom working on Pod  attr bar 

The name of the CRD "repro-sample" show up. The name of the Pod does not. The logs are from api/v1/repro_conversion.go. The versions are going between v1alpha1 and v1. I followed the kubebuilder scaffolds and book. 

If logs elsewhere would tell us more send a ptr. Thanks for looking !

**Comment by champak** [comment] 2020-06-02 20:19
And a get on the CRD looks like

$ kctl get repro.left.play.zone/repro-sample -o yaml | more
apiVersion: left.play.zone/v1
kind: Repro
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"left.play.zone/v1alpha1","kind":"Repro","metadata":{"annota
tions":{},"name":"repro-sample","namespace":"default"},"spec":{"foo":"bar","grap
h":{"dummy":"isthere","pod":{"metadata":{"name":"mia-pod-name"},"spec":{"contain
ers":[{"image":"busybox","name":"a-container"}]}}}}}
  creationTimestamp: "2020-06-02T19:42:30Z"
  generation: 1
  name: repro-sample
  namespace: default
  resourceVersion: "22387679"
  selfLink: /apis/left.play.zone/v1/namespaces/default/reproes/repro-sample
  uid: fac7fae5-3592-4925-a454-69a98e20e1bf
spec:
  foo: bar
  graph:
    dummy: ""
    pod:
      metadata: {}
      spec:
        containers: null
status: {}

The pod metadata is missing. Similar behavior for embedding other native types like PVCs or services. Perhaps I am missing some setting but found nothing yet.

**Comment by champak** [comment] 2020-06-04 19:38
@DirectXMan12  let me know if I try to get any other details etc. that may help. I hope the example provides enough info. One thing I had noted is that the meta-data was missing even before we hit the convert functions. For the v1alpha1 CR version we hit the reconcile loop before going to the convert callbacks  and the bits are already missing. That made me wonder if it is the apiserver that may have pruned the info due to some setting. The operator initialization log had

```
2020-06-04T19:15:50.982Z	INFO	controller-runtime.metrics	metrics server is starting to listen	{"addr": "127.0.0.1:8080"}
2020-06-04T19:15:50.982Z	INFO	controller-runtime.builder	skip registering a mutating webhook, admission.Defaulter interface is not implemented	{"GVK": "left.play.zone/v1alpha1, Kind=Repro"}
2020-06-04T19:15:50.982Z	INFO	controller-runtime.builder	skip registering a validating webhook, admission.Validator interface is not implemented	{"GVK": "left.play.zone/v1alpha1, Kind=Repro"}
2020-06-04T19:15:50.982Z	INFO	controller-runtime.webhook	registering webhook	{"path": "/convert"}
2020-06-04T19:15:50.982Z	INFO	controller-runtime.builder	conversion webhook enabled	{"object": {"metadata":{"creationTimestamp":null},"spec":{"graph":{"pod":{"metadata":{"creationTimestamp":null},"spec":{"containers":null}},"dummy":""}},"status":{}}}
2020-06-04T19:15:51.080Z	INFO	setup	starting manager
2020-06-04T19:15:51.082Z	INFO	controller-runtime.manager	starting metrics server	{"path": "/metrics"}
2020-06-04T19:15:51.182Z	INFO	controller-runtime.webhook.webhooks	starting webhook server
2020-06-04T19:15:51.183Z	INFO	controller-runtime.certwatcher	Updated current TLS certificate
2020-06-04T19:15:51.185Z	INFO	controller-runtime.webhook	serving webhook server	{"host": "", "port": 9443}
2020-06-04T19:15:51.186Z	INFO	controller-runtime.certwatcher	Starting certificate watcher
2020-06-04T19:16:08.575Z	DEBUG	controller-runtime.manager.events	Normal	{"object": {"kind":"ConfigMap","namespace":"metarepro-system","name":"controller-leader-election-helper","uid":"9bb0c9fc-a56d-4436-9a62-57329c1a3e77","apiVersion":"v1","resourceVersion":"22876473"}, "reason": "LeaderElection", "message": "metarepro-controller-manager-5575c95b5c-c9n48_6428cfcb-da12-4e36-8a6b-9d1e6e31aff6 became leader"}
2020-06-04T19:16:08.576Z	INFO	controller-runtime.controller	Starting EventSource	{"controller": "repro", "source": "kind source: /, Kind="}
2020-06-04T19:16:08.877Z	INFO	controller-runtime.controller	Starting Controller	{"controller": "repro"}
2020-06-04T19:16:08.977Z	INFO	controller-runtime.controller	Starting workers	{"controller": "repro", "worker count": 1}
```

**Comment by champak** [comment] 2020-06-09 21:17
@DirectXMan12 please let me know if you need any other info to take a look into this issue. Thanks !

**Comment by DirectXMan12** [comment] 2020-06-10 23:57
sorry.  Did some digging thursday / friday.  I think you're hitting unknown field elision -- need to confirm that, but I think it's because conversion requires `preserveUnknownFields: false`, which will strip fields from the under-specified ObjectMeta.  Related: #385, #395

**Comment by champak** [comment] 2020-06-11 20:08
@DirectXMan12 Thanks for taking a look ! If there is any hack that would allow crd conversion to work w/o needing preserveUnknownFields: false let me know and I can try it out. I could not tell if the changes from #385, #395 will get pulled into controller-gen main. I did not follow what functional need makes preserveUnknownFields: false mandatory. I can see it is desirable since dealing with conversion of unstructured data is ill-defined. But in many cases we merely want the unstructured blob to flow over to the new CRD version without changes. Would be nice to have a means for that.

**Comment by DirectXMan12** [comment] 2020-06-11 22:13
kubernetes itself requires `preserveUnknownFields: false` if conversion is enabled for v1beta1, and IIRC has it on by default in v1

**Comment by champak** [comment] 2020-06-11 22:44
@DirectXMan12 thanks for explaining ; in that case it sounds like something on the lines of #395 would be needed. I did not see updates on the issue since Jan ; is a different approach under consideration ? Think it would be essential to preserve at least a few common fields from ObjectMeta  like name, namespace to be able to make embeddable native resources work well in a versioned CRD.  Base types like replicasets embed podspecs and can handle version changes. Would be awesome to be able to do that with CRDs as well.

**Comment by champak** [comment] 2020-06-18 22:31
@DirectXMan12 is there any possibility of a fix or workaround for this issue in the near future ? Thanks.

**Comment by champak** [comment] 2020-07-08 21:48
@DirectXMan12 I see the review for #395 is still open. Any chance it will be available soon ? Else are there other options for getting around this issue ? Thanks

**Comment by champak** [comment] 2020-08-19 21:28
@DirectXMan12 @droot are the changes on  #395 planned for any upcoming release ? There does not seem to be a reasonable workaround. Using a custom version of ObjectMeta is not an option for anything that is already out there. Was hoping there would be a fix or the changes on #395 will get merged.

**Comment by DirectXMan12** [comment] 2020-09-11 22:15
@champak I've commented on #395.  I think it's pretty close to being good to go, it just needs a tweak.  Sorry about dropping the ball on that one.  IDK if the original author is still around, but if you have some bandwidth and want to pick it up, feel free.

**Comment by champak** [comment] 2020-09-15 12:31
@DirectXMan12 Thanks for getting back. I shall give it a shot.  Were you saying we need a crd option for controller-gen on the lines of trivialVersions or maxDescLen to turn this on ?

**Comment by DirectXMan12** [comment] 2020-09-21 23:51
> Were you saying we need a crd option for controller-gen on the lines of trivialVersions or maxDescLen to turn this on ?

Yeah, exactly.

Note that @sttts has a counter-proposal, so might be worth reconciling that (pun intended ;-) )

**Comment by champak** [comment] 2020-09-26 20:48
@DirectXMan12  I added a simple option for using #395 (see above). Pl take a look when you can and let me know what it needs. I could not find a decent way to test with a private version of controller-gen. The go get mechanism in the kubebuilder makefile want to install a published version. If you send a ptr on how to test it out shall run thru it. Thanks.

**Comment by champak** [comment] 2020-10-01 20:04
@DirectXMan12 just polling on this issue...
On a separate topic, how do we build a local controller-gen binary from the repo. Using the packaged test works but was wondering if there is some way to build the binary directly.

**Comment by DirectXMan12** [comment] 2020-12-08 23:04
> On a separate topic, how do we build a local controller-gen binary from the repo

`go build ./cmd/controller-gen` (or did you men something else?)

**Comment by champak** [comment] 2020-12-13 14:42
Thanks @DirectXMan12 I had been looking for a way to build a local version and use it with kubebuilder. I had built it like you suggested and then put in my path to prevent the kubebuilder Makefile from pulling the published version down. That worked OK but had wondered if there is better way etc.

**Comment by adux6991** [comment] 2020-12-18 08:47
I had the same issue!!! It had been extremely puzzling until I realized there is something to do with controller-gen. Thank you for raising it and developers for fixing it!

**Comment by dvaldivia** [comment] 2021-01-26 06:21
@champak did you found a solution?

**Comment by dvaldivia** [comment] 2021-01-26 06:28
It's still not clear to me what is causing the embedded `ObjectMeta` to be lost, if the original CRD "v1" had it, wouldn't it be transmitted to the webhook and then the conversion code would move it over? What am I missing?

**Comment by dvaldivia** [comment] 2021-01-26 06:36
I intercepted the very first call to the webhook for conversion and dumped the raw `ConversionReview`, which in my case has a `"desiredAPIVersion": "minio.min.io/v2",` and I can see the embedded metadata is already missing, if you see my `volumeClaimTemplate` has empty metadata, but even in the annotations you can see `kubectl.kubernetes.io/last-applied-configuration` the json there still has the metadata, this leads me to believe the problem is on the kubernetes API side, this is going from a CRD with trivial versions to a new CRD without trivial versions

```
{
  "kind": "ConversionReview",
  "apiVersion": "apiextensions.k8s.io/v1",
  "request": {
    "uid": "fc6c5800-23c3-4e68-8da2-fd74fb261d86",
    "desiredAPIVersion": "minio.min.io/v2",
    "objects": [
      {
        "apiVersion": "minio.min.io/v1",
        "kind": "Tenant",
        "metadata": {
          "annotations": {
            "kubectl.kubernetes.io/last-applied-configuration": "{\"apiVersion\":\"minio.min.io/v1\",\"kind\":\"Tenant\",\"metadata\":{\"annotations\":{\"prometheus.io/path\":\"/minio/prometheus/metrics\",\"prometheus.io/port\":\"9000\",\"prometheus.io/scrape\":\"true\"},\"labels\":{\"app\":\"minio\"},\"name\":\"minio\",\"namespace\":\"default\"},\"spec\":{\"certConfig\":{\"commonName\":\"\",\"dnsNames\":[],\"organizationName\":[]},\"console\":{\"consoleSecret\":{\"name\":\"console-secret\"},\"image\":\"minio/console:v0.3.26\",\"replicas\":2},\"credsSecret\":{\"name\":\"minio-creds-secret\"},\"image\":\"minio/minio:RELEASE.2020-11-19T23-48-16Z\",\"imagePullPolicy\":\"IfNotPresent\",\"mountPath\":\"/export\",\"podManagementPolicy\":\"Parallel\",\"requestAutoCert\":true,\"s3\":{\"bucketDNS\":false},\"zones\":[{\"servers\":4,\"volumeClaimTemplate\":{\"metadata\":{\"name\":\"data\"},\"spec\":{\"accessModes\":[\"ReadWriteOnce\"],\"resources\":{\"requests\":{\"storage\":\"1Ti\"}}}},\"volumesPerServer\":4}]}}\n",
            "prometheus.io/path": "/minio/prometheus/metrics",
            "prometheus.io/port": "9000",
            "prometheus.io/scrape": "true"
          },
          "creationTimestamp": "2021-01-26T06:19:15Z",
          "generation": 1,
          "labels": {
            "app": "minio"
          },
          "name": "minio",
          "namespace": "default",
          "uid": "dfb6e0ef-5855-4f1a-aa21-6b915fb942ce"
        },
        "spec": {
          "certConfig": {
            "commonName": "",
            "dnsNames": [],
            "organizationName": []
          },
          "console": {
            "consoleSecret": {
              "name": "console-secret"
            },
            "image": "minio/console:v0.3.26",
            "replicas": 2
          },
          "credsSecret": {
            "name": "minio-creds-secret"
          },
          "image": "minio/minio:RELEASE.2020-11-19T23-48-16Z",
          "imagePullPolicy": "IfNotPresent",
          "mountPath": "/export",
          "podManagementPolicy": "Parallel",
          "requestAutoCert": true,
          "s3": {
            "bucketDNS": false
          },
          "zones": [
            {
              "servers": 4,
              "volumeClaimTemplate": {
                "metadata": {},
                "spec": {
                  "accessModes": [
                    "ReadWriteOnce"
                  ],
                  "resources": {
                    "requests": {
                      "storage": "1Ti"
                    }
                  }
                }
              },
              "volumesPerServer": 4
            }
          ]
        },
        "status": {
          "availableReplicas": 4,
          "currentState": "Initialized"
        }
      }
    ]
  },
  "response": {
    "uid": "",
    "convertedObjects": null,
    "result": {
      "metadata": {}
    }
  }
}

```

**Comment by fjmacagno** [comment] 2021-03-18 16:34
Any further progress debugging this? It is causing problems with keda now too.

**Comment by dvaldivia** [comment] 2021-03-18 17:25
@fjmacagno I sent a PR to fix this, you could build using this PR and fix the problem https://github.com/kubernetes-sigs/controller-tools/pull/539

**Comment by ns-jisorce** [comment] 2021-07-05 07:35
Fixed by https://github.com/kubernetes-sigs/controller-tools/pull/557 no ?

**Closed** 2021-09-03 07:57 UTC
Labels: kind/bug, lifecycle/rotten, priority/critical-urgent

**Comment by sfc-gh-llin** [comment] 2022-07-21 01:46
> 

Yes, it's fixed now. Use the controller-gen crd option `crd:generateEmbeddedObjectMeta=true` will work

**Comment by imaskm** [comment] 2022-09-29 15:21
Hi guys, I tried with "crd:generateEmbeddedObjectMeta=true" and generated manifests and go code again but it still isn't working

`manifests: controller-gen ## Generate WebhookConfiguration, ClusterRole and CustomResourceDefinition objects.
	$(CONTROLLER_GEN) crd:generateEmbeddedObjectMeta=true rbac:roleName=manager-role crd webhook paths="./..." output:crd:artifacts:config=config/crd/bases


generate: controller-gen ## Generate code containing DeepCopy, DeepCopyInto, and DeepCopyObject method implementations.
	$(CONTROLLER_GEN) crd:generateEmbeddedObjectMeta=true object:headerFile="hack/boilerplate.go.txt" paths="./..."
`

**Comment by imaskm** [comment] 2022-09-29 16:34
Found the issue, I was using Makefile generated by Kubebuilder, after adding this flag "crd:generateEmbeddedObjectMeta=true" to "manifests" target, somehow the location of generated crd yaml was changed and I kept applying the older ones.

**Comment by Algatux** [comment] 2023-04-14 13:16
Using the "crd:generateEmbeddedObjectMeta=true" flag fixes the issue but it is generating two versions of the manifests:
- one fixed but in the wrong directory (config root)
- one still broken inside the crd base directory

**Comment by oscartrullols** [comment] 2023-09-20 11:21
> Using the "crd:generateEmbeddedObjectMeta=true" flag fixes the issue but it is generating two versions of the manifests:
> 
> * one fixed but in the wrong directory (config root)
> * one still broken inside the crd base directory

I was also getting similar results until I understood how the command works. At first, I was wrongly adding the `crd:generateEmbeddedObjectMeta=true` to the command and that adds a new generator outputing its own results. what we really want here is to replace the already present `crd` generator with the `crd:generateEmbeddedObjectMeta=true`.

That solved my issues without generating any extra files at unexpected folders

**Comment by Antirecord** [comment] 2023-10-16 06:40
> > Using the "crd:generateEmbeddedObjectMeta=true" flag fixes the issue but it is generating two versions of the manifests:
> > 
> > * one fixed but in the wrong directory (config root)
> > * one still broken inside the crd base directory
> 
> I was also getting similar results until I understood how the command works. At first, I was wrongly adding the `crd:generateEmbeddedObjectMeta=true` to the command and that adds a new generator outputing its own results. what we really want here is to replace the already present `crd` generator with the `crd:generateEmbeddedObjectMeta=true`.
> 
> That solved my issues without generating any extra files at unexpected folders

Hi! I im fixed my makefile, but controller-gen generating (double) role.yaml in crd/bases/ . What i should do ?

`.PHONY: manifests
manifests: controller-gen ## Generate WebhookConfiguration, ClusterRole and CustomResourceDefinition objects.
	$(CONTROLLER_GEN) rbac:roleName=manager-role crd:generateEmbeddedObjectMeta=true webhook paths="./..." output:artifacts:config=config/crd/bases
`

**Comment by laotoutou** [comment] 2023-12-01 17:07
I used `crd:generateEmbeddedObjectMeta=true`, it works! But this can't generate `creationTimestamp` field.
